#!/bin/sh
/usr/sbin/arangod -c /etc/arangodb/arangod.conf &
ARANGODB_PID=$!

# Wait for server to start
while : ; do bash -c "echo >/dev/tcp/localhost/8529" >/dev/null 2>&1 && break || sleep 1; done

# Create database if it does not exist
if [ $DATABASE_NAME ]; then
  echo Creating database $DATABASE_NAME unless exists
  arangosh --javascript.execute-string "db._createDatabase('$DATABASE_NAME')";
fi

# Kill it again
kill $ARANGODB_PID

# Wait for server to stop
while : ; do bash -c "echo >/dev/tcp/localhost/8529" >/dev/null 2>&1 && sleep 1 || break; done

# Start it again finally
echo Starting arangod finally
exec /usr/sbin/arangod -c /etc/arangodb/arangod.conf
